version: "3.6"

services:

  serpent:
    build:
      context: $PWD/serpent_docker
      dockerfile: serpent.dockerfile
    volumes:
      - type: bind
        source: $PWD/app
        target: /home/Serpent